ALTER TABLE "TargetingRuleConfig"
ADD COLUMN "minScoreToTarget" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN "maxBuyersPerOrder" INTEGER NOT NULL DEFAULT 20,
ADD COLUMN "cooldownHours" INTEGER NOT NULL DEFAULT 0;
